const PLACES = [
  {
    id: 4,
    order: 1,
    icon: "🫔",
    name: "Bolivian Llama Party",
    tagline: "Bolivian street food done with serious flair",
    description: "Born at the Queens Night Market, Bolivian Llama Party brought salteñas — flaky, juice-filled Bolivian hand pies — to the mainstream. The fillings rotate but the quality never dips. A true Queens success story.",
    cuisine: "Bolivian",
    address: "44-14 48th Ave, Sunnyside, Queens, NY 11377",
    coordinates: [40.73930, -73.92077],
    category: "snack",
    mustTry: "Salteñas, fried chicken sandwich",
    priceRange: "$",
    photo: "https://images.ctfassets.net/1aemqu6a6t65/4X7TtXV68rQ52O5TaL9rcR/d7099aab9266d72a2479babe7d7a37f8/Bolivian-Llama-Party-Sunnyside-Queens-NYC-Photo-VincentTullo-255.jpg?w=1200&h=800&q=75"
  },
  {
    id: 17,
    order: 2,
    icon: "🍗",
    name: "Jollibee",
    tagline: "The Filipino fast food giant, right in the heart of Little Manila",
    description: "The Woodside outpost of the beloved Filipino chain sits squarely in Little Manila, one of the most significant Filipino communities in the US. Chickenjoy — the signature crispy fried chicken — has a cult following that spans continents, and the sweet-style spaghetti is a rite of passage.",
    cuisine: "Filipino",
    address: "62-29 Roosevelt Ave, Woodside, Queens, NY 11377",
    coordinates: [40.7461, -73.9012],
    category: "savory",
    mustTry: "Chickenjoy fried chicken",
    priceRange: "$",
    hours: "Daily 8am–11pm"
  },
  {
    id: 1,
    order: 3,
    icon: "🍜",
    name: "Sripraphai Thai Restaurant",
    tagline: "Queens' most beloved Thai kitchen",
    description: "A Queens institution since 1990, Sripraphai serves fiercely authentic Thai food that draws devotees from across the city. The green papaya salad and crispy watercress salad are legendary, and the curries hit with genuine heat.",
    cuisine: "Thai",
    address: "64-13 39th Ave, Woodside, Queens, NY 11377",
    coordinates: [40.74645, -73.89924],
    category: "savory",
    mustTry: "Crispy watercress salad, drunken noodles with beef, curry puffs",
    priceRange: "$$",
    hours: "Thu–Tue 11am–9:30pm (closed Wed)",
    phone: "(718) 899-9599",
    website: "https://sripraphairestaurant.com",
    photo: "https://sripraphai.com/images/sripraphai-plate.jpg"
  },
  {
    id: 7,
    order: 4,
    icon: "🍖",
    name: "Ihawan",
    tagline: "Filipino BBQ and the smell of charcoal in Woodside",
    description: "A Woodside institution for Filipino grilled meats — pork belly, chicken inasal, and longanisa all cooked over live charcoal. The room is loud and warm, the rice is piled high, and the sawsawan dipping sauces are made in-house.",
    cuisine: "Filipino",
    address: "40-06 70th St, Woodside, Queens, NY 11377",
    coordinates: [40.74617, -73.89549],
    category: "savory",
    mustTry: "Pork belly BBQ",
    priceRange: "$$",
    hours: "Wed–Mon 11am–10pm",
    photo: "https://images.getbento.com/accounts/bd80d00f58702f8e2ae0ca229715e58d/media/images/37855ihawanbbq.jpg"
  },
  {
    id: 18,
    order: 5,
    icon: "🫓",
    name: "Dosa Delight",
    tagline: "South Indian vegetarian done right in Jackson Heights",
    description: "A Jackson Heights staple for South Indian cooking, Dosa Delight turns out crispy, paper-thin dosas alongside rich sambars and chutneys. It's kosher, fully vegetarian, and beloved by the neighborhood's large South Asian community. The masala dosa is essential.",
    cuisine: "South Indian",
    address: "35-66 73rd St, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74918, -73.89292],
    category: "savory",
    mustTry: "Masala dosa",
    priceRange: "$",
    hours: "Daily 10:30am–10pm"
  },
  {
    id: 26,
    order: 6,
    icon: "🥣",
    name: "Tong",
    tagline: "Bangladeshi street snacks on a Jackson Heights corner",
    description: "What started as a tiny street cart in 2018, Tong brought the flavors of Dhaka's street food scene to Jackson Heights. Fuchka — crispy hollow puri filled with spiced tamarind water — chotpoti, jhaal muri, and pitha are all made to order. It's the kind of snacking that's impossible to stop at just one.",
    cuisine: "Bangladeshi",
    address: "37-08 73rd St, Jackson Heights, Queens, NY 11372",
    coordinates: [40.748524, -73.892850],
    category: "snack",
    mustTry: "Fuchka, chotpoti, jhaal muri",
    priceRange: "$",
    hours: "Daily 2pm–12am",
    phone: "(929) 257-6996"
  },
  {
    id: 2,
    order: 7,
    icon: "🥟",
    name: "Phayul",
    tagline: "Jackson Heights' go-to Tibetan kitchen",
    description: "A warm, no-frills Tibetan restaurant above the Roosevelt Ave bustle that's beloved by the neighborhood's Tibetan community and adventurous eaters alike. The momos are handmade and generously filled, and the thukpa noodle soup is deeply comforting.",
    cuisine: "Tibetan",
    address: "37-65 74th St, FL 2, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74717, -73.89126],
    category: "savory",
    mustTry: "Steamed momos",
    priceRange: "$",
    hours: "Daily 11am–10pm",
    photo: "https://phayul.shop/public/media/phayul-shop/1.jpg"
  },
  {
    id: 5,
    order: 8,
    icon: "🍛",
    name: "Angel Indian",
    tagline: "Deep, spice-forward Indian cooking in Jackson Heights",
    description: "Jackson Heights is one of the best places in the world to eat Indian food, and this spot holds its own among serious competition. Expect bold curries, freshly made bread, and a room full of regulars who know exactly what they're ordering.",
    cuisine: "Indian",
    address: "75-18 37th Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74723, -73.89093],
    category: "savory",
    mustTry: "Lamb curry, chicken biryani",
    priceRange: "$$",
    photo: "https://culinarybackstreets.s3.us-east-2.amazonaws.com/culinarybackstreets/uploads/cb_queens_angel_dc_final_outside.jpg"
  },
  {
    id: 23,
    order: 9,
    icon: "🐟",
    name: "Zaab Zaab",
    tagline: "Michelin-listed Isan Thai — fiery, funky, and electric",
    description: "One of the most exciting Thai restaurants in New York, Zaab Zaab specializes in the bold, fermented flavors of northeastern Thailand's Isan region. The larb is funky and herbaceous, the papaya salad has real heat, and the grilled meats arrive with sticky rice and house-made jeow dipping sauces.",
    cuisine: "Thai (Isan)",
    address: "76-04 Woodside Ave, Elmhurst, Queens, NY 11373",
    coordinates: [40.74323, -73.88865],
    category: "savory",
    mustTry: "Larb, green papaya salad, grilled chicken, salt baked fish",
    priceRange: "$$",
    hours: "Mon–Fri 11:30am–3:30pm & 4:30pm–11pm, Sat–Sun 9am–11pm",
    phone: "(631) 526-1664"
  },
  {
    id: 6,
    order: 10,
    icon: "🌮",
    name: "Birria-Landia Food Truck",
    tagline: "The taco truck that made birria a New York obsession",
    description: "What started as a humble taco truck in Jackson Heights sparked a city-wide birria craze. The tacos are stuffed with slow-braised beef, crisped on the griddle, and served with a rich consomé for dipping. Get there early — they sell out.",
    cuisine: "Mexican",
    address: "Roosevelt Ave & 78th St, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74741, -73.88843],
    category: "savory",
    mustTry: "Birria tacos with consomé",
    priceRange: "$",
    photo: "https://birrialandia.com/wp-content/uploads/2024/05/taco-platter.jpg"
  },
  {
    id: 16,
    order: 11,
    icon: "🌽",
    name: "The Arepa Lady",
    tagline: "The legendary street cart that became a Queens institution",
    description: "Maria Piedad Cano spent decades working a charcoal cart on Roosevelt Ave before her sons helped her open a proper restaurant. The arepas — crispy outside, soft and cheesy within — are as good as they ever were. The chorizos and empanadas are not to be missed either.",
    cuisine: "Colombian",
    address: "77-17 37th Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74952, -73.88837],
    category: "snack",
    mustTry: "Arepa de choclo with cheese",
    priceRange: "$",
    hours: "Wed–Sun 5pm–11pm"
  },
  {
    id: 19,
    order: 12,
    icon: "🍜",
    name: "Ayada Thai",
    tagline: "Elmhurst's Thai gem — bold, fragrant, and deeply authentic",
    description: "Ayada has earned a devoted following for its fiercely authentic Thai cooking in a no-frills Elmhurst dining room. The curries are complex and aromatic, the papaya salad bites back, and the pad see ew is among the best in the city. A worthy rival to anything in Bangkok.",
    cuisine: "Thai",
    address: "77-08 Woodside Ave, Elmhurst, Queens, NY 11373",
    coordinates: [40.74357, -73.88778],
    category: "savory",
    mustTry: "Pad see ew, green curry, chive dumpling",
    priceRange: "$$",
    hours: "Mon–Fri 11:30am–10pm, Sat–Sun 11am–10pm",
    phone: "(718) 424-0844"
  },
  {
    id: 21,
    order: 13,
    icon: "🐓",
    name: "Eim Khao Mun Kai",
    tagline: "One dish done perfectly — Elmhurst's Thai chicken rice counter",
    description: "A tiny, focused Elmhurst counter that does one thing: khao mun kai, the Thai take on Hainanese poached chicken over fragrant rice with a rich broth and ginger-soy sauce. Simple, precise, and deeply satisfying. The line moves fast and the price is unbeatable.",
    cuisine: "Thai",
    address: "81-32 Broadway, Elmhurst, Queens, NY 11373",
    coordinates: [40.742874, -73.883302],
    category: "savory",
    mustTry: "Khao mun kai (Thai chicken rice)",
    priceRange: "$",
    hours: "Daily 10:30am–3pm & 3:30pm–8pm",
    phone: "(718) 424-7156"
  },
  {
    id: 27,
    order: 14,
    icon: "🥘",
    name: "La Pequeña Colombia",
    tagline: "A taste of Colombia's coast in the heart of Jackson Heights",
    description: "A Jackson Heights institution since the 1970s, La Pequeña Colombia is the neighborhood anchor for Colombian home cooking. Bandeja paisa, sancocho, lechona, and chicharrón are all done with conviction. It's the kind of restaurant where whole families pile in on weekends and the portions are never small.",
    cuisine: "Colombian",
    address: "83-27 Roosevelt Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.747894, -73.882190],
    category: "savory",
    mustTry: "Bandeja paisa, sancocho",
    priceRange: "$$",
    hours: "Mon–Thu & Sun 11am–11pm, Fri–Sat 11am–12am",
    phone: "(718) 478-8700"
  },
  {
    id: 28,
    order: 15,
    icon: "🍗",
    name: "Urubamba",
    tagline: "NYC's oldest Peruvian restaurant, still going strong since 1976",
    description: "Open since 1976, Urubamba is the oldest family-run Peruvian restaurant in New York City. The pollo a la brasa is the anchor — slow-roasted over charcoal with Peruvian spices — but the ceviche, lomo saltado, and weekend chicha morada are all essential. A living piece of Queens food history.",
    cuisine: "Peruvian",
    address: "86-20 37th Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.7501019, -73.8797895],
    category: "savory",
    mustTry: "Pollo a la brasa, ceviche",
    priceRange: "$$",
    hours: "Mon–Fri 12pm–10pm, Sat–Sun 9:30am–10pm",
    phone: "(718) 672-2224"
  },
  {
    id: 20,
    order: 16,
    icon: "🐷",
    name: "Taiwanese Gourmet",
    tagline: "Cash-only Taiwanese street food hiding in plain sight in Elmhurst",
    description: "A cash-only, no-frills counter in Elmhurst serving deeply authentic Taiwanese street food — braised pork rice, scallion pancakes, three-cup chicken, and offal dishes that reward the adventurous. Known locally as 老華西街 (Old Huaxi Street), it's a rare find outside of Taipei.",
    cuisine: "Taiwanese",
    address: "84-02 Broadway, Elmhurst, Queens, NY 11373",
    coordinates: [40.73993, -73.87865],
    category: "savory",
    mustTry: "Braised pork rice, scallion pancake",
    priceRange: "$",
    hours: "Mon–Fri 11am–10pm",
    phone: "(718) 429-4818"
  },
  {
    id: 22,
    order: 17,
    icon: "🦐",
    name: "Mariscos El Submarino",
    tagline: "Fresh Mexican seafood in the heart of Jackson Heights",
    description: "A Jackson Heights gem for Mexican coastal cooking — tostadas stacked with shrimp or octopus ceviche, cold aguachile verde, and seafood cocktails spiked with lime and hot sauce. It's the kind of food that makes you feel like you're eating on a beach somewhere on the Pacific coast.",
    cuisine: "Mexican Seafood",
    address: "88-05 Roosevelt Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.7484366, -73.8781062],
    category: "savory",
    mustTry: "Aguachile, shrimp tostada",
    priceRange: "$$",
    hours: "Mon–Thu 11am–10pm, Fri–Sat 11am–11pm, Sun 10am–10pm",
    phone: "(718) 685-2780"
  },
  {
    id: 9,
    order: 18,
    icon: "🍋",
    name: "Benfaremo — The Lemon Ice King of Corona",
    tagline: "A Queens legend, one scoop at a time since 1944",
    description: "Standing at the corner of 108th Street since 1944, the Lemon Ice King is as much a Queens landmark as it is a dessert shop. The lemon ice is bracingly tart and ice-cold, made from a recipe that hasn't changed in 80 years. The line wraps around the block on hot days — join it.",
    cuisine: "Italian Ice",
    address: "52-02 108th St, Corona, Queens, NY 11368",
    coordinates: [40.74320, -73.85509],
    category: "sweet",
    mustTry: "Lemon ice",
    priceRange: "$",
    hours: "Daily 10am–11pm (seasonal)",
    photo: "https://thesciencesurvey.com/wp-content/uploads/2024/11/0-1200x900.jpeg"
  },
  {
    id: 12,
    order: 19,
    icon: "🌶️",
    name: "Mountain House Flushing",
    tagline: "Bold Sichuan and Hunan flavors in the heart of Flushing",
    description: "Mountain House brings the fiery, numbing heat of Sichuan cooking to a Flushing dining room that fills up fast. The dry-pot dishes and cold appetizers are standouts, and the spice levels are taken seriously.",
    cuisine: "Chinese (Sichuan)",
    address: "39-16 Prince St, Ste G03, Flushing, Queens, NY 11354",
    coordinates: [40.75920, -73.83260],
    category: "savory",
    mustTry: "Dry-pot dishes",
    priceRange: "$$",
    photo: "https://cdn.vox-cdn.com/uploads/chorus_image/image/73339273/SzechuanMountainHouse_Interior_7108_SELECT.0.jpg"
  },
  {
    id: 15,
    order: 20,
    icon: "🥟",
    name: "Nan Xiang Xiao Long Bao",
    tagline: "Flushing's gold standard for soup dumplings",
    description: "The name most locals cite when you ask where to get xiao long bao in Flushing. The soup dumplings are delicate, generously filled, and arrive in bamboo steamers with a pool of hot broth inside each one. Bite carefully, dip in ginger-vinegar, repeat.",
    cuisine: "Chinese (Shanghainese)",
    address: "39-16 Prince St, Flushing, Queens, NY 11354",
    coordinates: [40.75928, -73.83260],
    category: "savory",
    mustTry: "Pork xiao long bao",
    priceRange: "$$",
    hours: "Daily 11am–10pm"
  },
  {
    id: 3,
    order: 21,
    icon: "🔥",
    name: "White Bear",
    tagline: "Cult-favorite wontons in Flushing's back streets",
    description: "A postage-stamp takeout counter in Flushing with an almost mythical reputation. The menu is barely a dozen items but everyone comes for one thing: the #6, pork and chive wontons tossed in a fiery, numbing chili oil. Cash only, arrive early.",
    cuisine: "Chinese",
    address: "135-02 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75886, -73.83169],
    category: "savory",
    mustTry: "#6 wontons in chili oil",
    priceRange: "$",
    hours: "Daily 11am–8pm",
    photo: "https://res.cloudinary.com/the-infatuation/image/upload/q_auto,f_auto/images/NYC_WhiteBear_WontonWHotSauce_KatePrevite_00002_qjo8by"
  },
  {
    id: 11,
    order: 22,
    icon: "🥟",
    name: "Handmade Dumpling",
    tagline: "No-frills Flushing dumplings, made fresh all day",
    description: "A tiny counter in Flushing's dumpling corridor where the dough is rolled and filled by hand in plain sight. The pork and cabbage dumplings are juicy and cheap, and the turnover is so fast they're always fresh off the pan.",
    cuisine: "Chinese",
    address: "35-46 Union St, Flushing, Queens, NY 11354",
    coordinates: [40.7642581, -73.8282469],
    category: "savory",
    mustTry: "Pan-fried pork dumplings",
    priceRange: "$"
  },
  {
    id: 13,
    order: 23,
    icon: "🫘",
    name: "Soy Bean Chen Flower",
    tagline: "Silky tofu flower from a Flushing institution",
    description: "A beloved Flushing counter that's been ladling out douhua — silky, just-set tofu flower — for years. You choose sweet (ginger syrup) or savory (soy sauce, scallion, dried shrimp), and both are deeply comforting. An essential stop for anyone eating their way through Flushing.",
    cuisine: "Chinese (Tofu)",
    address: "135-26 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75910, -73.83100],
    category: "snack",
    mustTry: "Douhua (tofu flower)",
    priceRange: "$",
    photo: "https://loganlo.com/wp-content/uploads/2024/07/20240714_122321.jpg"
  },
  {
    id: 14,
    order: 24,
    icon: "🍚",
    name: "Joe's Steam Rice Roll",
    tagline: "Silky cheung fun made to order in Flushing",
    description: "Joe's turns out some of the best cheung fun outside of Hong Kong — translucent rice noodle sheets steamed to order, stuffed with shrimp, beef, or char siu, and finished with a sweet soy drizzle. The texture is impossibly smooth. Get multiple orders.",
    cuisine: "Chinese (Cantonese)",
    address: "136-21 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75993, -73.82931],
    category: "snack",
    mustTry: "Shrimp cheung fun",
    priceRange: "$",
    photo: "https://media.timeout.com/images/105501168/750/422/image.jpg"
  },
  {
    id: 8,
    order: 25,
    icon: "🏮",
    name: "New World Mall Food Court",
    tagline: "A whole world of Chinese regional food underground",
    description: "Descend into the basement of Flushing's New World Mall and you're in one of the most exciting food courts in the country. Stalls serve hand-pulled noodles, scallion pancakes, stinky tofu, bubble tea, and obscure regional Chinese dishes you won't find anywhere else in the city.",
    cuisine: "Chinese (regional)",
    address: "136-20 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75934, -73.82916],
    category: "savory",
    mustTry: "Hand-pulled noodles",
    priceRange: "$",
    hours: "Daily 10am–10pm",
    photo: "https://thatbestbite.com/wp-content/uploads/2013/11/08.jpg"
  },
  {
    id: 24,
    order: 26,
    icon: "🌭",
    name: "Hahm Ji Bach",
    tagline: "Legendary Korean comfort food, open nearly round the clock",
    description: "A Flushing institution beloved for soondae (blood sausage), gopchang (grilled intestines), and deeply satisfying Korean comfort dishes. The hours are almost comically generous — open 24 hours most of the week — and the late-night crowd is as much a part of the experience as the food.",
    cuisine: "Korean",
    address: "40-11 149th Pl, Flushing, Queens, NY 11354",
    coordinates: [40.7631009, -73.8149165],
    category: "savory",
    mustTry: "Soondae, gopchang",
    priceRange: "$$",
    hours: "Mon 10am–12am, Tue–Sat open 24hrs, Sun 12am–10pm",
    phone: "(718) 460-9289"
  },
  {
    id: 25,
    order: 27,
    icon: "🥩",
    name: "Jongro BBQ",
    tagline: "Full Korean BBQ in Flushing's Murray Hill",
    description: "A serious Korean BBQ spot in Flushing's Murray Hill neighborhood, where quality cuts of beef and pork are grilled tableside over charcoal. The banchan spread is generous, the ventilation actually works, and the whole experience is exactly what a proper Korean BBQ night out should feel like.",
    cuisine: "Korean BBQ",
    address: "155-14 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.7637921, -73.8094885],
    category: "savory",
    mustTry: "Chadolbaegi, galbi",
    priceRange: "$$$",
    hours: "Daily 11am–11pm",
    phone: "(718) 939-9330"
  },
  {
    id: 10,
    order: 28,
    icon: "🍺",
    name: "Bohemian Hall & Beer Garden",
    tagline: "NYC's oldest beer garden, still going strong in Astoria",
    description: "Open since 1910, Bohemian Hall is the last surviving Czech beer garden in New York City. The sprawling outdoor garden fits hundreds under the trees, with pitchers of Czech lager, hearty Eastern European food, and a genuine neighborhood-party atmosphere that's impossible to fake.",
    cuisine: "Czech / Beer Garden",
    address: "29-19 24th Ave, Astoria, Queens, NY 11102",
    coordinates: [40.77284, -73.91563],
    category: "bonus",
    mustTry: "Czech lager by the pitcher",
    priceRange: "$$",
    hours: "Mon–Fri 5pm–2am, Sat–Sun 12pm–2am",
    photo: "https://images.ctfassets.net/1aemqu6a6t65/74rNWw3zU6HMZ7Balx4Wj/ab5c8a7ac7846336e9a1bf5cc2360e6a/beer_bohemianhallandbeergarden_claytoncotterell_mg_1247?w=1200&h=800&q=75"
  }
];
