const PLACES = [
  {
    id: 7,
    order: 1,
    name: "Ihawan",
    tagline: "Filipino BBQ and the smell of charcoal in Woodside",
    description: "A Woodside institution for Filipino grilled meats — pork belly, chicken inasal, and longanisa all cooked over live charcoal. The room is loud and warm, the rice is piled high, and the sawsawan dipping sauces are made in-house.",
    cuisine: "Filipino",
    address: "40-06 70th St, Woodside, Queens, NY 11377",
    coordinates: [40.74617, -73.89549],
    category: "savory",
    mustTry: "Pork belly BBQ",
    priceRange: "$$",
    hours: "Wed–Mon 11am–10pm",
    photo: "https://images.getbento.com/accounts/bd80d00f58702f8e2ae0ca229715e58d/media/images/37855ihawanbbq.jpg"
  },
  {
    id: 1,
    order: 2,
    name: "Sripraphai Thai Restaurant",
    tagline: "Queens' most beloved Thai kitchen",
    description: "A Queens institution since 1990, Sripraphai serves fiercely authentic Thai food that draws devotees from across the city. The green papaya salad and crispy watercress salad are legendary, and the curries hit with genuine heat.",
    cuisine: "Thai",
    address: "64-13 39th Ave, Woodside, Queens, NY 11377",
    coordinates: [40.74645, -73.89924],
    category: "savory",
    mustTry: "Crispy watercress salad",
    priceRange: "$$",
    hours: "Thu–Tue 11am–9:30pm (closed Wed)",
    phone: "(718) 899-9599",
    website: "https://sripraphairestaurant.com",
    photo: "https://sripraphai.com/images/sripraphai-plate.jpg"
  },
  {
    id: 4,
    order: 3,
    name: "Bolivian Llama Party",
    tagline: "Bolivian street food done with serious flair",
    description: "Born at the Queens Night Market, Bolivian Llama Party brought salteñas — flaky, juice-filled Bolivian hand pies — to the mainstream. The fillings rotate but the quality never dips. A true Queens success story.",
    cuisine: "Bolivian",
    address: "44-14 48th Ave, Sunnyside, Queens, NY 11377",
    coordinates: [40.73930, -73.92077],
    category: "snack",
    mustTry: "Salteñas",
    priceRange: "$",
    photo: "https://images.ctfassets.net/1aemqu6a6t65/4X7TtXV68rQ52O5TaL9rcR/d7099aab9266d72a2479babe7d7a37f8/Bolivian-Llama-Party-Sunnyside-Queens-NYC-Photo-VincentTullo-255.jpg?w=1200&h=800&q=75"
  },
  {
    id: 2,
    order: 4,
    name: "Phayul",
    tagline: "Jackson Heights' go-to Tibetan kitchen",
    description: "A warm, no-frills Tibetan restaurant above the Roosevelt Ave bustle that's beloved by the neighborhood's Tibetan community and adventurous eaters alike. The momos are handmade and generously filled, and the thukpa noodle soup is deeply comforting.",
    cuisine: "Tibetan",
    address: "37-65 74th St, FL 2, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74717, -73.89126],
    category: "savory",
    mustTry: "Steamed momos",
    priceRange: "$",
    hours: "Daily 11am–10pm",
    photo: "https://phayul.shop/public/media/phayul-shop/1.jpg"
  },
  {
    id: 5,
    order: 5,
    name: "Angel of Harlem / Angel Indian",
    tagline: "Deep, spice-forward Indian cooking in Jackson Heights",
    description: "Jackson Heights is one of the best places in the world to eat Indian food, and this spot holds its own among serious competition. Expect bold curries, freshly made bread, and a room full of regulars who know exactly what they're ordering.",
    cuisine: "Indian",
    address: "75-18 37th Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74723, -73.89093],
    category: "savory",
    mustTry: "Lamb curry",
    priceRange: "$$",
    photo: "https://culinarybackstreets.s3.us-east-2.amazonaws.com/culinarybackstreets/uploads/cb_queens_angel_dc_final_outside.jpg"
  },
  {
    id: 6,
    order: 6,
    name: "Birria-Landia",
    tagline: "The taco truck that made birria a New York obsession",
    description: "What started as a humble taco truck in Jackson Heights sparked a city-wide birria craze. The tacos are stuffed with slow-braised beef, crisped on the griddle, and served with a rich consomé for dipping. Get there early — they sell out.",
    cuisine: "Mexican",
    address: "Roosevelt Ave & 78th St, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74741, -73.88843],
    category: "savory",
    mustTry: "Birria tacos with consomé",
    priceRange: "$",
    photo: "https://birrialandia.com/wp-content/uploads/2024/05/taco-platter.jpg"
  },
  {
    id: 16,
    order: 7,
    name: "The Arepa Lady",
    tagline: "The legendary street cart that became a Queens institution",
    description: "Maria Piedad Cano spent decades working a charcoal cart on Roosevelt Ave before her sons helped her open a proper restaurant. The arepas — crispy outside, soft and cheesy within — are as good as they ever were. The chorizos and empanadas are not to be missed either.",
    cuisine: "Colombian",
    address: "77-17 37th Ave, Jackson Heights, Queens, NY 11372",
    coordinates: [40.74952, -73.88837],
    category: "snack",
    mustTry: "Arepa de choclo with cheese",
    priceRange: "$",
    hours: "Wed–Sun 5pm–11pm"
  },
  {
    id: 9,
    order: 8,
    name: "Benfaremo — The Lemon Ice King of Corona",
    tagline: "A Queens legend, one scoop at a time since 1944",
    description: "Standing at the corner of 108th Street since 1944, the Lemon Ice King is as much a Queens landmark as it is a dessert shop. The lemon ice is bracingly tart and ice-cold, made from a recipe that hasn't changed in 80 years. The line wraps around the block on hot days — join it.",
    cuisine: "Italian Ice",
    address: "52-02 108th St, Corona, Queens, NY 11368",
    coordinates: [40.74320, -73.85509],
    category: "sweet",
    mustTry: "Lemon ice",
    priceRange: "$",
    hours: "Daily 10am–11pm (seasonal)",
    photo: "https://thesciencesurvey.com/wp-content/uploads/2024/11/0-1200x900.jpeg"
  },
  {
    id: 3,
    order: 9,
    name: "White Bear",
    tagline: "Cult-favorite wontons in Flushing's back streets",
    description: "A postage-stamp takeout counter in Flushing with an almost mythical reputation. The menu is barely a dozen items but everyone comes for one thing: the #6, pork and chive wontons tossed in a fiery, numbing chili oil. Cash only, arrive early.",
    cuisine: "Chinese",
    address: "135-02 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75886, -73.83169],
    category: "savory",
    mustTry: "#6 wontons in chili oil",
    priceRange: "$",
    hours: "Daily 11am–8pm",
    photo: "https://res.cloudinary.com/the-infatuation/image/upload/q_auto,f_auto/images/NYC_WhiteBear_WontonWHotSauce_KatePrevite_00002_qjo8by"
  },
  {
    id: 8,
    order: 10,
    name: "New World Mall Food Court",
    tagline: "A whole world of Chinese regional food underground",
    description: "Descend into the basement of Flushing's New World Mall and you're in one of the most exciting food courts in the country. Stalls serve hand-pulled noodles, scallion pancakes, stinky tofu, bubble tea, and obscure regional Chinese dishes you won't find anywhere else in the city.",
    cuisine: "Chinese (regional)",
    address: "136-20 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75934, -73.82916],
    category: "savory",
    mustTry: "Hand-pulled noodles",
    priceRange: "$",
    hours: "Daily 10am–10pm",
    photo: "https://thatbestbite.com/wp-content/uploads/2013/11/08.jpg"
  },
  {
    id: 11,
    order: 11,
    name: "Handmade Dumpling",
    tagline: "No-frills Flushing dumplings, made fresh all day",
    description: "A tiny counter in Flushing's dumpling corridor where the dough is rolled and filled by hand in plain sight. The pork and cabbage dumplings are juicy and cheap, and the turnover is so fast they're always fresh off the pan.",
    cuisine: "Chinese",
    address: "35-46 Union St, Flushing, Queens, NY 11354",
    coordinates: [40.75890, -73.83150],
    category: "savory",
    mustTry: "Pan-fried pork dumplings",
    priceRange: "$"
  },
  {
    id: 12,
    order: 12,
    name: "Mountain House Flushing",
    tagline: "Bold Sichuan and Hunan flavors in the heart of Flushing",
    description: "Mountain House brings the fiery, numbing heat of Sichuan cooking to a Flushing dining room that fills up fast. The dry-pot dishes and cold appetizers are standouts, and the spice levels are taken seriously.",
    cuisine: "Chinese (Sichuan)",
    address: "39-16 Prince St, Ste G03, Flushing, Queens, NY 11354",
    coordinates: [40.75920, -73.83260],
    category: "savory",
    mustTry: "Dry-pot dishes",
    priceRange: "$$",
    photo: "https://cdn.vox-cdn.com/uploads/chorus_image/image/73339273/SzechuanMountainHouse_Interior_7108_SELECT.0.jpg"
  },
  {
    id: 13,
    order: 13,
    name: "Soy Bean Chen Flower",
    tagline: "Silky tofu flower from a Flushing institution",
    description: "A beloved Flushing counter that's been ladling out douhua — silky, just-set tofu flower — for years. You choose sweet (ginger syrup) or savory (soy sauce, scallion, dried shrimp), and both are deeply comforting. An essential stop for anyone eating their way through Flushing.",
    cuisine: "Chinese (Tofu)",
    address: "135-26 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75910, -73.83100],
    category: "snack",
    mustTry: "Douhua (tofu flower)",
    priceRange: "$",
    photo: "https://loganlo.com/wp-content/uploads/2024/07/20240714_122321.jpg"
  },
  {
    id: 14,
    order: 14,
    name: "Joe's Steam Rice Roll",
    tagline: "Silky cheung fun made to order in Flushing",
    description: "Joe's turns out some of the best cheung fun outside of Hong Kong — translucent rice noodle sheets steamed to order, stuffed with shrimp, beef, or char siu, and finished with a sweet soy drizzle. The texture is impossibly smooth. Get multiple orders.",
    cuisine: "Chinese (Cantonese)",
    address: "136-21 Roosevelt Ave, Flushing, Queens, NY 11354",
    coordinates: [40.75993, -73.82931],
    category: "snack",
    mustTry: "Shrimp cheung fun",
    priceRange: "$",
    photo: "https://media.timeout.com/images/105501168/750/422/image.jpg"
  },
  {
    id: 15,
    order: 15,
    name: "Nan Xiang Xiao Long Bao",
    tagline: "Flushing's gold standard for soup dumplings",
    description: "The name most locals cite when you ask where to get xiao long bao in Flushing. The soup dumplings are delicate, generously filled, and arrive in bamboo steamers with a pool of hot broth inside each one. Bite carefully, dip in ginger-vinegar, repeat.",
    cuisine: "Chinese (Shanghainese)",
    address: "39-16 Prince St, Flushing, Queens, NY 11354",
    coordinates: [40.75928, -73.83260],
    category: "savory",
    mustTry: "Pork xiao long bao",
    priceRange: "$$",
    hours: "Daily 11am–10pm"
  },
  {
    id: 10,
    order: 16,
    name: "Bohemian Hall & Beer Garden",
    tagline: "NYC's oldest beer garden, still going strong in Astoria",
    description: "Open since 1910, Bohemian Hall is the last surviving Czech beer garden in New York City. The sprawling outdoor garden fits hundreds under the trees, with pitchers of Czech lager, hearty Eastern European food, and a genuine neighborhood-party atmosphere that's impossible to fake.",
    cuisine: "Czech / Beer Garden",
    address: "29-19 24th Ave, Astoria, Queens, NY 11102",
    coordinates: [40.77284, -73.91563],
    category: "bonus",
    mustTry: "Czech lager by the pitcher",
    priceRange: "$$",
    hours: "Mon–Fri 5pm–2am, Sat–Sun 12pm–2am",
    photo: "https://images.ctfassets.net/1aemqu6a6t65/74rNWw3zU6HMZ7Balx4Wj/ab5c8a7ac7846336e9a1bf5cc2360e6a/beer_bohemianhallandbeergarden_claytoncotterell_mg_1247?w=1200&h=800&q=75"
  }
];
